### ISSUE TITLE
'listen.exe' failure

### ISSUE THREAD

**Issue by gvanem** [mvaneerde/blog#140]
I found this project and the `listen/listen/main.cpp` example
(trying to add Text-to-Speech to one of my own programs).

First creating a file `hello-world.txt` with only `Hello world` and running
`listen.exe --file hello-world.txt`, always fails with 
`ERROR:ISpStream::BindToFile failed: hr = 0x800c000d`

According to `%VSINSTALLDIR%\Common7\Tools\errlook.exe`, the code `0x800c000d` is 
`Unknown protocol` (or `Den angitte protokollen er ukjent.` in Norwegian).

Which is `INET_E_UNKNOWN_PROTOCOL`. What has Inet to do with such SAPI-stuff and how can
I make this example work?

I'm on Win-10.  Build 19045, Home (version 22H2, OS-build 19045.5198).

Thanks in advance.

**Comment by gvanem** [comment]
But the sample `say.exe "Hello world"` works just fine (?!)

**Comment by mvaneerde** [comment]
`say.exe` is text-to-speech. If you type some text into the command line, or give it a text file like `hello-world.txt`, the computer will read it out loud.

`listen.exe` is speech-to-text. If you talk into the microphone, or give it a pre-recorded audio file like `hello-world.wav`, the computer will listen and type out what it hears.

The error message is complaining that `hello-world.txt` doesn't seem to be an audio file

**Comment by gvanem** [comment]
> The error message is complaining that hello-world.txt doesn't seem to be an audio file

Ah. Brain fart. But perhaps you have some ideas for a threaded version of `say.exe`? I've used this as a basic for my own
program, but absolutely needs a non-blocking speak feature. 

First, do I have to call `CoInitializeEx (NULL, COINIT_MULTITHREADED)` instead?

**Comment by mvaneerde** [comment]
`hr = pSpVoice->Speak(text, SPF_DEFAULT, &stream);`

If I read [the documentation](https://learn.microsoft.com/en-us/previous-versions/office/developer/speech-technologies/jj127460(v=msdn.10)) correctly, you can change `SPF_DEFAULT` to `SPF_ASYNC` to have the text spoken asynchronously
